# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuitui" do
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Darwin_x86_64.tar.gz"
      sha256 "ee93a9a13d1ddde72d9bb56bbfaf64e2a1f9123c43c14d91fc0e3f27011a225c"
    end
    on_arm do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Darwin_arm64.tar.gz"
      sha256 "93e43194a1b74fa30ba1eed1af3491f7e481874343ae98bc58976ada2ea643da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Linux_x86_64.tar.gz"
      sha256 "57417e1a2258dfcea7d90f7b6de6ef8771b6fe01eefa0538924b9b1df47a71fb"
    end
    on_arm do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Linux_arm64.tar.gz"
      sha256 "2a924eea13a7a3ba1120248012f6ad30c3b9c7b647b07daa1334126bfab9645c"
    end
  end

  name "tuitui"
  desc "Terminal user interface for Jujutsu (jj) version control"
  homepage "https://github.com/frederickbeaulieu/tuitui"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git-delta",
      "jj",
    ]

  binary "tuitui"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuitui"] if OS.mac?
  end

  # No zap stanza required

end
