# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuitui" do
  version "0.4.1"

  on_macos do
    on_intel do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Darwin_x86_64.tar.gz"
      sha256 "e21b92af681934da32f12b8fc9b65a692e2f09322259847b744448e44d4e859e"
    end
    on_arm do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Darwin_arm64.tar.gz"
      sha256 "562c1a749e494d28b8cbb8c0925199568db97857e440e443dac41ecd6a2f8a57"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Linux_x86_64.tar.gz"
      sha256 "ddd095c3b152a569745ee2aa287353daffe1fb1d3a183a4967609d95a0e59f1a"
    end
    on_arm do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Linux_arm64.tar.gz"
      sha256 "1ad95c21051f57c33bd91a133ad0670a2c51c0f8c0101df751f3eb2a09d65ec1"
    end
  end

  name "tuitui"
  desc "Terminal user interface for Jujutsu (jj) version control"
  homepage "https://github.com/frederickbeaulieu/tuitui"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git-delta",
      "jj",
    ]

  binary "tuitui"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuitui"] if OS.mac?
  end

  # No zap stanza required

end
