# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuitui" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Darwin_x86_64.tar.gz"
      sha256 "ccc57beb4be1e93b14d1fc80606b82a34d28e392a7e68af78c7ec4ac9728fcb7"
    end
    on_arm do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Darwin_arm64.tar.gz"
      sha256 "6071475ff764bb4fb5e544d8b065a65fb5e281c8b5e29bdb46bf5c9dd1a22c39"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Linux_x86_64.tar.gz"
      sha256 "865b0cc15bc39f26d239d903abe81d8fb48ea250ca97be6fe97646e7fa008ecd"
    end
    on_arm do
      url "https://github.com/frederickbeaulieu/tuitui/releases/download/v#{version}/tuitui_#{version}_Linux_arm64.tar.gz"
      sha256 "2a370fd5160dbc782bd5e07e816fb9ab2a9b38915705f1967c8322ed46d49e85"
    end
  end

  name "tuitui"
  desc "Terminal user interface for Jujutsu (jj) version control"
  homepage "https://github.com/frederickbeaulieu/tuitui"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git-delta",
      "jj",
    ]

  binary "tuitui"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuitui"] if OS.mac?
  end

  # No zap stanza required

end
